version: '3.7'

services:
  ui:
    image: city-library-ui:latest
    container_name: city-library-ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - web

networks:
  web:
    driver: "bridge"
